---
- name: "Ubuntu version"
  debug:
    msg: "Ubuntu version: {{ ansible_distribution }} {{ ansible_distribution_version }}"
   
- name: "Add multiverse repo"
  apt_repository:
    repo: "{{item}}"
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
  become: yes

- block:
    - name: Remove the EOL message of the day if one exists.
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/update-motd.d/99-esm
        - /run/motd.dynamic
      become: yes

    - name: Create /etc/apt/apt.conf.d/local
      file:
        path: /etc/apt/apt.conf.d/local
        state: touch
      become: yes

    - name: Add apt config used to workaround do-release-upgrade
      lineinfile:
        path: /etc/apt/apt.conf.d/local
        line: 'DPkg::options { "--force-confdef"; "--force-confnew"; }'
      become: yes
      
    - name: Remove old packages
      shell: apt autoremove --purge
      become: yes

    - name: Upgrade all packages to the latest version
      apt: update_cache=yes upgrade=dist autoclean=yes
      become: yes

    - name: Remove old packages
      shell: apt autoremove --purge
      become: yes

    - name: Ensure update-manager-core is installed.
      apt: name=update-manager-core state=present
      become: yes

    - name: Restart server
      shell: sleep 2 && shutdown -r now "Ansible system package upgraded" removes=/var/run/reboot-required
      async: 1
      poll: 0
      become: yes
      ignore_errors: true

    - name: Wait for server to reboot.
      wait_for_connection:
      become: no

    - name: Run do-release-upgrade non-interactively.
      command: do-release-upgrade -f DistUpgradeViewNonInteractive
      become: yes

    - name: Restart server
      shell: sleep 2 && shutdown -r now "Ansible system package upgraded" removes=/var/run/reboot-required
      async: 1
      poll: 0
      become: yes
      ignore_errors: true

    - name: Wait for server to reboot.
      wait_for_connection:
      become: no

    - name: Upgrade all packages to the latest version post distro upgrade
      apt: update_cache=yes upgrade=dist autoclean=yes
      become: yes
      
    - name: Restart server
      shell: sleep 2 && shutdown -r now "Ansible system package upgraded" removes=/var/run/reboot-required
      async: 1
      poll: 0
      become: yes
      ignore_errors: true

    - name: Wait for server to reboot.
      wait_for_connection:
      become: no

  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version != '16.04'

- name: Remove apt config used to workaround do-release-upgrade
  file:
    path: /etc/apt/apt.conf.d/local
    state: absent
  become: yes
  tags:
    - upgrade
    
- name: Remove old packages
  shell: apt autoremove --purge
  become: yes
  tags:
    - upgrade

- name: Safe upgrade all packages to the latest version
  apt: update_cache=yes upgrade=safe autoclean=yes
  become: true
  tags:
    - upgrade

- name: Remove old packages
  shell: apt autoremove --purge
  become: yes
  tags:
    - upgrade

- name: Reboot if required
  shell: sleep 2 && shutdown -r now "Ansible system package upgraded" removes=/var/run/reboot-required
  async: 1
  poll: 0
  become: yes
  ignore_errors: true
  tags:
    - upgrade

- name: Wait for server to reboot.
  wait_for_connection:
  become: no
  tags:
    - upgrade

- name: "Validate timezone variable"
  stat: path=/usr/share/zoneinfo/{{ timezone }}
  register: timezone_path
  changed_when: false

- name: "Explain timezone error"
  fail: msg="{{ timezone }} is not a valid timezone. For a list of valid timezones, check https://php.net/manual/en/timezones.php"
  when: not timezone_path.stat.exists

- name: "Get current timezone"
  command: cat /etc/timezone
  register: current_timezone
  changed_when: false

- name: "Set timezone"
  command: timedatectl set-timezone {{ timezone }}
  when: current_timezone.stdout != timezone
  become: yes

- name: "Set the hostname in /etc/hostname"
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined

- name: "Set the hostname"
  shell: hostname {{ hostname }}
  when: hostname is defined

- name: "Update /etc/hosts"
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ hostname }}' owner=root group=root mode=0644
  when: hostname is defined

- name: "Install common packages for 16.04"
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - python-software-properties
    - python-pip
    - htop
    - ncdu
    - wget
    - curl
    - mysql-client
    - python-mysqldb
    - acl
    - zip
    - unzip
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: "Install common packages for 18.04"
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - software-properties-common
    - python-pip
    - htop
    - ncdu
    - wget
    - curl
    - mysql-client
    - python-mysqldb
    - acl
    - zip
    - unzip
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'
